# Generated by Django 4.1 on 2022-09-27 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='new_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default=False, max_length=30)),
                ('profile', models.FileField(default=False, upload_to='')),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktitle', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('completed', models.BooleanField()),
                ('deadline', models.DateField()),
                ('unique_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.new_user')),
            ],
        ),
    ]
