# Generated by Django 4.1 on 2022-09-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user',
            name='designation',
            field=models.CharField(choices=[('manager', 'Manager'), ('team lead', 'Team Lead'), ('developer', 'Developer')], default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='profile',
            field=models.ImageField(default=False, upload_to='avatars'),
        ),
    ]
