# Generated by Django 4.1 on 2022-09-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_alter_new_user_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskDesc',
            field=models.TextField(default=False),
        ),
    ]
