# Generated by Django 4.1 on 2022-09-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_alter_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskDesc',
            field=models.TextField(blank=True),
        ),
    ]
