# Generated by Django 4.1 on 2022-09-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='developer',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
