# Generated by Django 4.1 on 2022-09-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0008_task_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AlterField(
            model_name='new_user',
            name='designation',
            field=models.CharField(choices=[('', '-----Select Designationr-----'), ('manager', 'Manager'), ('team lead', 'Team Lead'), ('developer', 'Developer')], default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
