# Generated by Django 4.1 on 2022-10-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0010_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
