# Generated by Django 4.1.1 on 2022-10-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0011_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user',
            name='designation',
            field=models.CharField(choices=[('', '-----Select Designationr-----'), ('Manager', 'Manager'), ('Team lead', 'Team Lead'), ('Developer', 'Developer')], default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Working on it', 'Working on it'), ('Stuck', 'Stuck'), ('Done', 'Done')], default='Working on it', max_length=30),
        ),
    ]
